---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: virtualmachines.crd.cloud.antrea.io
spec:
  group: crd.cloud.antrea.io
  names:
    kind: VirtualMachine
    listKind: VirtualMachineList
    plural: virtualmachines
    shortNames:
    - vm
    singular: virtualmachine
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.provider
      name: Cloud-Provider
      type: string
    - jsonPath: .status.virtualPrivateCloud
      name: Virtual-Private-Cloud
      type: string
    - jsonPath: .status.status
      name: Status
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: VirtualMachine is the Schema for the virtualmachines API A virtualMachine
          object is created automatically based on matching criteria specification
          of CloudEntitySelector.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: VirtualMachineSpec defines the desired state of VirtualMachine.
            type: object
          status:
            description: VirtualMachineStatus defines the observed state of VirtualMachine
              It contains observable parameters.
            properties:
              error:
                description: Error is current error, if any, of the VirtualMachine.
                type: string
              networkInterfaces:
                description: NetworkInterfaces is array of NetworkInterfaces attached
                  to this VirtualMachine.
                items:
                  description: NetworkInterfaceReference references to NetworkInterface.
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                  type: object
                type: array
              networkPolicies:
                additionalProperties:
                  type: string
                description: NetworkPolicies indicates NetworkPolicy status on this
                  VirtualMachine.
                type: object
              provider:
                description: Provider specifies cloud provider of this VirtualMachine.
                enum:
                - Azure
                - AWS
                type: string
              status:
                description: Status indicates current state of the VirtualMachine.
                type: string
              tags:
                additionalProperties:
                  type: string
                description: Tags of this VirtualMachine. A corresponding label is
                  also generated for each tag.
                type: object
              virtualPrivateCloud:
                description: VirtualPrivateCloud is the virtual private cloud this
                  VirtualMachine belongs to.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
